version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "sebastienrousseau"
    labels:
      - "ci/cd"
      - "automated"
    groups:
      github-actions:
        patterns:
          - "*"
