#!/usr/bin/env python3
"""Import the site's photographs from the local stock library into
static/img/photos/, cropped and re-encoded for this site's budgets.

Why local copies, not the CDN
-----------------------------
The site promises same-origin loading: its Content-Security-Policy is
`img-src 'self' data:` and the demo page tells readers every request
stays on pain001.com. Hotlinking cloudcdn.pro would break both.

Why our own derivatives
-----------------------
The library's 1200px files run to 160 KB. At 8K (a 7680px viewport, where
every photo on the homepage is on screen at once) that alone breaks the
300 KiB route budget. Each photo is centre-cropped to one aspect ratio,
so its box can be reserved without layout shift, and written at 480, 800
and 1200px at WebP quality 72.

Provenance: every file below carries its Unsplash photo ID in its name;
photos are used under the Unsplash License. Source library:
cloudcdn.pro/stocks/images (sebastienrousseau/cloudcdn.pro).

Usage: python3 scripts/import_photos.py [/path/to/cloudcdn.pro/stocks/images]
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "static" / "img" / "photos"
DEFAULT_SRC = Path.home() / "Code/Public/JavaScript/cloudcdn.pro/stocks/images"

MAP = ROOT / "scripts" / "page_photos.json"
NOTICES = ROOT / "THIRD_PARTY_NOTICES.md"
CREDITS_START = "<!-- photo-credits:start (generated by scripts/import_photos.py) -->"
CREDITS_END = "<!-- photo-credits:end -->"

# Homepage sections: slug -> aspect of the box the photo fills.
HOME_ASPECT = {
    "hero-city": (21, 9),
    "facade-grid": (3, 2),
    "data-centre": (3, 2),
    "columns": (3, 2),
    "bank-of-england": (4, 3),
    "city-blue-hour": (16, 9),
}
WIDTHS = (480, 800, 1200)
# The homepage banner is full-bleed, so it also ships 1600 and 2400.
WIDE = {"hero-city": (800, 1200, 1600, 2400)}
# Page-hero bands keep one shape at every screen size (CSS aspect-ratio,
# inside the content column), so what is cropped here is all that is ever
# cropped. Sources must be landscape: a portrait photo forced to 2:1 loses
# three quarters of its height and reads as a slice.
BAND_DIR = OUT / "band"
BAND_ASPECT = (2, 1)
BAND_WIDTHS = (640, 768, 960, 1280, 1600)
BAND_QUALITY = 60
# Every file also ships as AVIF (about a quarter smaller at the same
# visual quality); pages offer it first through <picture>, WebP after.
AVIF_QUALITY = 45
# A band is its page's largest paint, so its AVIF is held to a byte budget
# per width: the highest quality from AVIF_LADDER that fits, never below
# the last rung. Busy photos (aerial cities, tiled walls) land lower;
# simple ones keep AVIF_QUALITY.
BAND_AVIF_BUDGET = {640: 12_000, 768: 15_000, 960: 20_000, 1280: 22_000, 1600: 28_000}
# The homepage banner is its LCP too (the other homepage photos are lazy).
HOME_AVIF_BUDGET = {"hero-city": {800: 16_000, 1200: 24_000, 1600: 32_000, 2400: 64_000}}
AVIF_LADDER = (45, 40, 36, 32, 28, 25)
MIN_SOURCE_ASPECT = 1.4
# Vertical focus for a band crop (0 top, 1 bottom) where the automatic
# placement is wrong.
BAND_FOCUS = {"jonathan-chng-7_WyzplsaSE": 0.1, "planet-volumes-MT5g52DsGf4-unsplash": 1.0}
# Names as the photographers publish them, where the file stem cannot say.
NAMES = {
    "francais-a-londres": "Français à Londres",
    "cmophoto-net": "cmophoto.net",
    "chuttersnap": "CHUTTERSNAP",
    "rawpixel-com": "rawpixel.com",
    "fomstock-com": "fomstock.com",
    "henry-&-co": "Henry & Co.",
    # Stems that name a subject, not a person: credit the source link only.
    "usa": "Pexels contributor",
    "inside": "Pexels contributor",
}


# Unsplash IDs that are not the last 11 characters of their stem.
IDS = {"benjamin-davies-Oja2ty_9ZLMb": ("benjamin-davies", "Oja2ty_9ZLMb")}


def photo_source(stem: str) -> str | None:
    """Licence source of a library stem, or None when the site may not use
    it. Only Unsplash (photographer-<11 char id>) and Pexels
    (photographer-<numeric id>) photos are used, each under its own
    LICENSES/ file; Unsplash+ (Getty) and unnamed library files are not."""
    if stem.startswith(("getty-images", "pixabay", "sebastien-rousseau")):
        return None
    core = stem.removesuffix("-unsplash")
    if re.search(r"-\d{5,}$", core):
        return "pexels"
    if stem in IDS or re.search(r"-[A-Za-z0-9_-]{11}$", core) and re.search(r"[A-Z_\d]", core[-11:]):
        return "unsplash"
    return None


def band_path(stem: str) -> str:
    """Site path prefix of a page band; the folder carries the licence."""
    return f"/img/photos/band/{photo_source(stem)}/{stem}"


def credit(stem: str) -> tuple[str, str]:
    """(photographer, photo ID) from a library stem. Unsplash IDs are 11
    chars and may contain hyphens, so they are taken from the end."""
    core = stem.removesuffix("-unsplash")
    if stem in IDS:
        who, pid = IDS[stem]
    elif photo_source(stem) == "pexels":
        who, pid = core.rsplit("-", 1)
    else:
        who, pid = core[:-12], core[-11:]
    return NAMES.get(who, who.replace("-", " ").title()), pid


def source(src: Path, stem: str) -> Path:
    for name in (f"{stem}.webp", f"{stem}-1920.webp"):
        if (src / name).exists():
            return src / name
    raise FileNotFoundError(stem)


def crop(im: "Image.Image", aspect: tuple[int, int]) -> "Image.Image":
    w, h = im.size
    target = aspect[0] / aspect[1]
    if w / h > target:
        nw = round(h * target)
        left = (w - nw) // 2
        return im.crop((left, 0, left + nw, h))
    nh = round(w / target)
    top = (h - nh) // 2
    return im.crop((0, top, w, top + nh))


def band(im: "Image.Image", focus: float | None) -> "Image.Image":
    """2:1 crop of a landscape photo. Unless a focus is given, the window
    sits where the photo has the most detail (edge energy per row), so a
    skyline keeps its towers rather than a band of empty sky."""
    from PIL import ImageFilter

    w, h = im.size
    nh = min(h, round(w * BAND_ASPECT[1] / BAND_ASPECT[0]))
    nw = round(nh * BAND_ASPECT[0] / BAND_ASPECT[1])
    left = (w - nw) // 2
    if focus is None:
        small = im.convert("L").resize((64, 64 * h // w or 1))
        edges = small.filter(ImageFilter.FIND_EDGES)
        rows = [sum(edges.getpixel((x, y)) for x in range(small.width)) for y in range(small.height)]
        win = max(1, round(len(rows) * nh / h))
        sums = [sum(rows[i : i + win]) for i in range(len(rows) - win + 1)]
        best = max(range(len(sums)), key=sums.__getitem__)
        # Pull halfway back towards centre: detail-seeking alone hugs edges.
        focus = (best / max(1, len(rows) - win) + 0.5) / 2
    top = round((h - nh) * focus)
    return im.crop((left, top, left + nw, top + nh))


def save(im: "Image.Image", out: Path, width: int, aspect: tuple[int, int], quality: int,
         avif_budget: int | None = None) -> Path:
    """Write the WebP at `out` and its AVIF twin; return the AVIF path."""
    height = round(width * aspect[1] / aspect[0])
    small = im.resize((width, height), Image.LANCZOS)
    small.save(out, "WEBP", quality=quality, method=6)
    avif = out.with_suffix(".avif")
    for q in AVIF_LADDER if avif_budget else (AVIF_QUALITY,):
        small.save(avif, "AVIF", quality=q, speed=4)
        if not avif_budget or avif.stat().st_size <= avif_budget:
            break
    print(f"{out.relative_to(ROOT)}  {width}x{height}  {out.stat().st_size // 1024} KB "
          f"(avif {avif.stat().st_size // 1024} KB)")
    return avif


def write_credits(rows: list[tuple[str, str, str, str]]) -> None:
    table = ["| Used for | Photographer | Source |", "| :--- | :--- | :--- |"]
    for use, who, pid, stem in rows:
        if photo_source(stem) == "pexels":
            link = f"[Pexels {pid}](https://www.pexels.com/photo/{pid}/)"
        else:
            link = f"[Unsplash {pid}](https://unsplash.com/photos/{pid})"
        table.append(f"| {use} | {who} | {link} |")
    text = NOTICES.read_text(encoding="utf-8")
    a, b = text.index(CREDITS_START), text.index(CREDITS_END)
    NOTICES.write_text(text[: a + len(CREDITS_START)] + "\n\n" + "\n".join(table) + "\n\n" + text[b:], encoding="utf-8")


def main() -> int:
    global Image
    from PIL import Image  # only the importer needs Pillow, not the build

    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    spec = json.loads(MAP.read_text(encoding="utf-8"))
    home, pages = spec["homepage"], spec["pages"]
    stems = list(home.values()) + list(pages.values())
    dupes = sorted({s for s in stems if stems.count(s) > 1})
    if dupes:
        print(f"each photo is used once; repeated: {dupes}", file=sys.stderr)
        return 1
    refused = sorted(s for s in stems if photo_source(s) is None)
    if refused:
        print(f"not an Unsplash or Pexels photo: {refused}", file=sys.stderr)
        return 1
    for sub in ("unsplash", "pexels"):
        (BAND_DIR / sub).mkdir(parents=True, exist_ok=True)
    OUT.mkdir(parents=True, exist_ok=True)
    BAND_DIR.mkdir(parents=True, exist_ok=True)
    written: set[Path] = set()
    rows = []
    for slug, stem in home.items():
        aspect = HOME_ASPECT[slug]
        im = crop(Image.open(source(src, stem)).convert("RGB"), aspect)
        for width in WIDE.get(slug, WIDTHS):
            out = OUT / f"{slug}-{width}.webp"
            budget = HOME_AVIF_BUDGET.get(slug, {}).get(width)
            written |= {out, save(im, out, width, aspect, 72, budget)}
        if photo_source(stem) != "unsplash":
            print(f"homepage photos sit under the Unsplash annotation: {stem}", file=sys.stderr)
            return 1
        rows.append((f"homepage: {slug}", *credit(stem), stem))
    for page, stem in pages.items():
        im = Image.open(source(src, stem)).convert("RGB")
        if im.width / im.height < MIN_SOURCE_ASPECT:
            print(f"/{page}/: {stem} is {im.width}x{im.height}; bands need landscape "
                  f"photos (at least {MIN_SOURCE_ASPECT}:1)", file=sys.stderr)
            return 1
        strip = band(im, BAND_FOCUS.get(stem))
        for width in BAND_WIDTHS:
            out = BAND_DIR / photo_source(stem) / f"{stem}-{width}.webp"
            written |= {out, save(strip, out, width, BAND_ASPECT, BAND_QUALITY, BAND_AVIF_BUDGET[width])}
        rows.append((f"/{page}/" if page else "locale home pages", *credit(stem), stem))
    # Files this map no longer names are stale derivatives; remove them.
    stale = [*OUT.glob("*.webp"), *OUT.glob("*.avif"), *BAND_DIR.rglob("*.webp"), *BAND_DIR.rglob("*.avif")]
    for old in stale:
        if old not in written:
            old.unlink()
            print(f"removed {old.relative_to(ROOT)}")
    write_credits(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
