#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2023-2026 Sebastien Rousseau
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Compose a GitHub release's title and notes in the portfolio's format.

Every release page follows one layout (the "Release Page Format" rule in
~/Code/AGENTS.md, modelled on github/github-mcp-server's releases):

    title   pain001.com 0.0.8                  (no "v")
    body    ## Highlights ⭐️                    hand-written, 2-4 bullets
            ## What's Changed                  generated by GitHub
            ## New Contributors                generated, only when any
            ## Checksums                       SHA256SUMS of the assets
            **Full Changelog**: <compare URL>  generated

Only the Highlights are written by hand, in docs/releases/vX.Y.Z.md; the
rest comes from GitHub's generate-notes API, so the pull-request list and
the compare link are never retyped. A tag with no pull requests before it
(the first) gets its commits listed in the same shape instead.

Usage:
  python3 scripts/release_notes.py --tag vX.Y.Z --title
  python3 scripts/release_notes.py --tag vX.Y.Z --sums dist/SHA256SUMS --out notes.md
  python3 scripts/release_notes.py --check     # every docs/releases file

Needs `gh` authenticated (GH_TOKEN in CI) for everything but --title and
--check.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT = "pain001.com"
REPO = "sebastienrousseau/pain001.github.io"
NOTES = ROOT / "docs" / "releases"
TAG = re.compile(r"v(\d+)\.(\d+)\.(\d+)")
HEADING = "## Highlights ⭐️"
BULLET = re.compile(r"^\* \*\*[^*]+\*\*: \S")


def fail(message: str) -> None:
    raise SystemExit(f"[release-notes] {message}")


def title(tag: str) -> str:
    return f"{PROJECT} {tag[1:]}"


def highlights(tag: str) -> str:
    """The hand-written Highlights for a tag, checked against the format."""
    path = NOTES / f"{tag}.md"
    if not path.is_file():
        fail(f"{path.relative_to(ROOT)} is missing; write the release's Highlights first")
    text = path.read_text(encoding="utf-8").strip()
    lines = text.splitlines()
    if lines[0] != HEADING:
        fail(f"{path.name}: must start with '{HEADING}'")
    if any(line.startswith("#") for line in lines[1:]):
        fail(f"{path.name}: holds the Highlights only; the other sections are generated")
    bullets = [line for line in lines if line.startswith("* ")]
    if not 2 <= len(bullets) <= 4:
        fail(f"{path.name}: needs 2 to 4 Highlights bullets, has {len(bullets)}")
    for bullet in bullets:
        if not BULLET.match(bullet):
            fail(f"{path.name}: bullets read '* **Feature**: sentence.', not {bullet[:40]!r}")
    # GitHub's own sections have no blank line after the heading; match it.
    return HEADING + "\n" + "\n".join(lines[1:]).strip() + "\n"


def gh(*args: str) -> str:
    return subprocess.run(["gh", *args], check=True, capture_output=True, text=True).stdout


def semver(tag: str) -> tuple[int, ...]:
    return tuple(int(n) for n in TAG.fullmatch(tag).groups())


def previous_tag(tag: str) -> str | None:
    tags = subprocess.run(["git", "tag", "--list", "v*"], cwd=ROOT, check=True,
                          capture_output=True, text=True).stdout.split()
    older = sorted((t for t in tags if TAG.fullmatch(t) and semver(t) < semver(tag)), key=semver)
    return older[-1] if older else None


def generated(tag: str, previous: str | None) -> str:
    args = ["api", f"repos/{REPO}/releases/generate-notes", "-f", f"tag_name={tag}"]
    if previous:
        args += ["-f", f"previous_tag_name={previous}"]
    return json.loads(gh(*args))["body"]


def first_release_changes(tag: str) -> str:
    """What's Changed for a tag with no pull requests: its commits, oldest first."""
    commits = json.loads(gh("api", f"repos/{REPO}/commits?sha={tag}&per_page=100"))
    lines = [f"* {c['commit']['message'].splitlines()[0]} by @{(c.get('author') or {}).get('login', 'unknown')}"
             f" in https://github.com/{REPO}/commit/{c['sha']}" for c in reversed(commits)]
    return "## What's Changed\n" + "\n".join(lines) + "\n"


def compose(tag: str, sums: str) -> str:
    previous = previous_tag(tag)
    body = generated(tag, previous)
    changelog = re.search(r"^\*\*Full Changelog\*\*: \S+$", body, re.MULTILINE)
    if not changelog:
        fail(f"GitHub's generated notes for {tag} have no Full Changelog line")
    sections = body[:changelog.start()].strip()
    if not sections.startswith("## What's Changed"):
        if sections:
            fail(f"unexpected generated notes for {tag}: {sections[:60]!r}")
        sections = first_release_changes(tag).strip()
    parts = [highlights(tag), sections + "\n"]
    if sums.strip():
        parts.append("## Checksums\n\n```\n" + sums.strip() + "\n```\n")
    parts.append(changelog.group(0) + "\n")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag")
    parser.add_argument("--title", action="store_true", help="print the release title and stop")
    parser.add_argument("--sums", type=Path, help="SHA256SUMS of the release assets")
    parser.add_argument("--out", type=Path, help="write the notes here instead of stdout")
    parser.add_argument("--check", action="store_true", help="check every docs/releases file")
    args = parser.parse_args(argv)
    if args.check:
        files = sorted(NOTES.glob("v*.md"))
        for path in files:
            highlights(path.stem)
        print(f"[release-notes] {len(files)} Highlights file(s) in the release format")
        return 0
    if not args.tag or not TAG.fullmatch(args.tag):
        fail(f"--tag must be a release tag such as v0.0.9, not {args.tag!r}")
    if args.title:
        print(title(args.tag))
        return 0
    notes = compose(args.tag, args.sums.read_text(encoding="utf-8") if args.sums else "")
    if args.out:
        args.out.write_text(notes, encoding="utf-8")
    else:
        sys.stdout.write(notes)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
